
#### ___           ____            ####
#  /  _ \ _ __ ___| __ )  __ _ _ __   #
#  | | | | '__/ _ |  _ \ / _` | '_ \  #
#  | |_| | | |  __| |_) | (_| | | | | #
#  \___/ |_|  \___|____/\__,_|_| |_|  #
####          By Hekates-          ####

#   ___         _   _    _
#  / __> ___ _| |_| |_ <_>._ _  ___  ___
#  \__ \/ ._> | | | |  | || ' |/ . |<_-<
#  <___/\___. |_| |_|  |_||_|_|\_. |/__/
#                              <___'
#-Banned Ores-#
ores:
  -